
version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: tasks-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./data/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: tasks-webserver
      working_dir: /var/www
      volumes:
          - ./application:/var/www
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./logs/nginx/:/var/log/nginx          
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: tasks-php-fpm
      working_dir: /var/www
      volumes:
        - ./application:/var/www
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
